CREATE TABLE QUIZZES
(
    QUIZ_ID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(100),
    DESCRIPTION TINYTEXT,
    PRIMARY KEY(QUIZ_ID)
);

CREATE TABLE QUESTIONS
(
    QUESTION_ID INT NOT NULL AUTO_INCREMENT,
    TEXT TINYTEXT,
    QUIZ_ID INT NOT NULL,
    PRIMARY KEY(QUESTION_ID),
    FOREIGN KEY(QUIZ_ID) REFERENCES QUIZZES(QUIZ_ID)
);

CREATE TABLE ALTERNATIVES
(
    ALTERNATIVE_ID INT NOT NULL AUTO_INCREMENT,
    TEXT VARCHAR(100),
    IS_CORRECT BIT NOT NULL,
    QUESTION_ID INT NOT NULL,
    PRIMARY KEY(ALTERNATIVE_ID),
    FOREIGN KEY(QUESTION_ID) REFERENCES QUESTIONS (QUESTION_ID)
);


INSERT INTO QUIZZES(TITLE, DESCRIPTION) VALUES ('Exempelquiz', 'Detta är ett exempelquiz för att demonstrera hemsidan. Kan även användas som mall när nya quiz ska läggas in i hemsidans databas.');

INSERT INTO QUESTIONS(TEXT, QUIZ_ID) VALUES ('Detta är en fråga!', 1);

INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Rätt Svar', 1, 1);
INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Fel Svar', 0, 1);
INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Fel Svar', 0, 1);
INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Fel Svar', 0, 1);


INSERT INTO QUESTIONS(TEXT, QUIZ_ID) VALUES ('Här är en till fråga men med endast två alternativ!', 1);

INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Svar 1', 0, 2);
INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Svar 2', 1, 2);

INSERT INTO QUESTIONS(TEXT, QUIZ_ID) VALUES ('Detta är sista frågan', 1);

INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Ok', 1, 3);


/*----------------------------------------------------------------------*/

INSERT INTO QUIZZES(TITLE, DESCRIPTION) VALUES ('Webbprogrammering', 'Detta quiz testar dina kunskaper om webbprogrammering.');


INSERT INTO QUESTIONS(TEXT, QUIZ_ID) VALUES ('Vad står förkortningen HTML för?', 2);

INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('HyperText Markup Language', 1, 4);
INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('HyperLinks Markup Language', 0, 4);
INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Helpful Markup Language', 0, 4);


INSERT INTO QUESTIONS(TEXT, QUIZ_ID) VALUES ('Vem skapade språket HTML?', 2);

INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Tim Berners-Lee', 1, 5);
INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Steve Jobs', 0, 5);
INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Bjarne Stroustrup', 0, 5);
INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Bill Gates', 0, 5);


INSERT INTO QUESTIONS(TEXT, QUIZ_ID) VALUES ('Vad står förkortningen CSS för?', 2);

INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Cascading Style Sheets', 1, 6);
INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('CSS: Style Sheets', 0, 6);
INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Construction Style Sheets', 0, 6);


INSERT INTO QUESTIONS(TEXT, QUIZ_ID) VALUES ('Vart inkluderas normalt en stilmall i en HTML-fil?', 2);

INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Inom en <head>-tagg', 1, 7);
INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Längst upp i dokumentet', 0, 7);
INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Inom en <html>-tagg', 0, 7);
INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Inom en <include>-tagg', 0, 7);


INSERT INTO QUESTIONS(TEXT, QUIZ_ID) VALUES ('Vilken av följande är inte en korrekt HTML-tagg?', 2);

INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('<button>', 0, 8);
INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('<input>', 0, 8);
INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('<a>', 0, 8);
INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('<b>', 0, 8);
INSERT INTO ALTERNATIVES(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('<c>', 1, 8);

