CREATE TABLE QUIZZES
(
    QUIZ_ID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(100),
    DESCRIPTION TINYTEXT,
    PRIMARY KEY(QUIZ_ID)
);

CREATE TABLE QUESTIONS
(
    QUESTION_ID INT NOT NULL AUTO_INCREMENT,
    TEXT TINYTEXT,
    QUIZ_ID INT NOT NULL,
    PRIMARY KEY(QUESTION_ID),
    FOREIGN KEY(QUIZ_ID) REFERENCES QUIZZES(QUIZ_ID)
);

CREATE TABLE ANSWERS
(
    ANSWER_ID INT NOT NULL AUTO_INCREMENT,
    TEXT VARCHAR(100),
    IS_CORRECT BIT NOT NULL,
    QUESTION_ID INT NOT NULL,
    PRIMARY KEY(ANSWER_ID),
    FOREIGN KEY(QUESTION_ID) REFERENCES QUESTIONS(QUESTION_ID)
);

INSERT INTO QUIZZES(TITLE, DESCRIPTION) VALUES ('Test titel', 'Beskrivande text här');

INSERT INTO QUESTIONS(TEXT, QUIZ_ID) VALUES ('Här är frågan osv...', 1);

INSERT INTO ANSWERS(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Alternativ 1', 0, 1);
INSERT INTO ANSWERS(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Alternativ 2', 1, 1);
INSERT INTO ANSWERS(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Alternativ 3', 0, 1);
INSERT INTO ANSWERS(TEXT, IS_CORRECT, QUESTION_ID) VALUES ('Alternativ 4', 0, 1);